name: Publish TechDocs
description: Generate and publish TechDocs
inputs:
  publisher:
    description: awsS3 | googleGcs | azureBlobStorage
    required: true
  credentials:
    description:
      Credentials required to authenticate with your publisher through the techdocs-cli
      For GCS, provide the JSON service account key file, as a base64-encoded string in GOOGLE_APPLICATION_CREDENTIALS
      For AWS, provide AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, delimited by a space
      For Azure, provide AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET delimited by a space
    required: true
  bucket:
    description: In case of AWS or GCS this is the bucket name. In case of Azure, the container name
    required: true
  entity:
    description: Entity uid separated by / in namespace/kind/name order (case-sensitive). For example default/Component/myEntity
    required: true
  sourceDir:
    description: 'Source directory for repositories containing nested documentation'
    default: .
  azureAccountName:
    description: Azure account name, required if publisher is Azure
  azureAccountKey:
    description: Azure Storage Account key. Use as an alternative authentication method to the credentials input
  awsRoleArn:
    description: Optional AWS ARN of role to be assumed
  awsEndpoint:
    description: Optional AWS endpoint to send requests to

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # the 2 steps below can be removed if you aren't using plantuml in your documentation
    - name: setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: "Install plantuml"
      shell: bash
      run: |
        curl -o plantuml.jar -L http://sourceforge.net/projects/plantuml/files/plantuml.1.2021.4.jar/download
        echo "be498123d20eaea95a94b174d770ef94adfdca18  plantuml.jar" | sha1sum -c -
        mv plantuml.jar /opt/plantuml.jar
        mkdir -p "$HOME/.local/bin"
        echo $'#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> "$HOME/.local/bin/plantuml"
        chmod +x "$HOME/.local/bin/plantuml"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        sudo apt-get install -y graphviz

    - name: 'Install techdocs cli'
      shell: bash
      run: |
        npm i @techdocs/cli
    - name: 'Install python deps'
      shell: bash
      run: |
        pip install mkdocs-techdocs-core==1.2.0 mkdocs-awesome-pages-plugin==2.5.0 mkdocs-nav-enhancements==0.9.1 mkdocs-exclude==1.0.2 mkdocs-section-index==0.3.5
    - name: 'Publish docs'
      shell: bash
      run: |
        ./main.sh \
        -a ${{ inputs.publisher }} \
        -b ${{ inputs.credentials }} \
        -c ${{ inputs.bucket }} \
        -d ${{ inputs.entity }} \
        -e ${{ inputs.sourceDir }} \
        -f ${{ inputs.azureAccountName }} \
        -g ${{ inputs.azureAccountKey }} \
        -h ${{ inputs.awsRoleArn }} \
        -i ${{ inputs.awsEndpoint }}
